### ISSUE TITLE
Disambiguate Drupal 7 and 8, move Drupal 8 to a separate repo

### ISSUE THREAD

**Issue by fureigh** [18F/cf-ex-drupal#19]
* [x] Make a separate repo for Drupal 8.
* [x] Update the description of this one to be Drupal-7-specific while supporting discoverability of the other one.
* [x] When appropriate, remove Drupal 8 pieces from this one.
* [x] [same] Change directory structure.

**Comment by pburkholder** [comment]
https://github.com/18f/cf-ex-drupal8

**Comment by fureigh** [comment]
Now that cf-ex-drupal8 is functional, it's time to move on to the remaining steps here! PR to come.
